- name: Build DLL
      run: |
        echo Building DLL... >> logs/build.log
        if not exist src\RustAlkadCheat2588.cpp (
          echo Error: RustAlkadCheat2588.cpp not found in src/ directory >> logs/build.log
          dir src /s /b >> logs/build.log 2>&1
          exit 1
        )
        echo RustAlkadCheat2588.cpp found >> logs/build.log
        if not exist zlib\zlib.lib (
          echo Error: zlib.lib not found in zlib/ directory >> logs/build.log
          dir zlib /s /b >> logs/build.log 2>&1
          exit 1
        )
        echo zlib.lib found >> logs/build.log
        cl /D UNICODE /D _UNICODE /EHsc /Zi /Fe:RustAlkadCheat.dll /LD src/RustAlkadCheat2588.cpp /I imgui-master /I minhook-master/include /I zlib /I json-develop/single_include /link /LIBPATH:zlib zlib.lib user32.lib d3d11.lib dxgi.lib shell32.lib ws2_32.lib
        if %ERRORLEVEL% NEQ 0 (
          echo Build failed, check compiler output above >> logs/build.log
          exit 1
        )
        echo Build successful >> logs/build.log
      shell: cmd
