name: Build Rust Alkad Cheat 2588

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Клонирует репозиторий на виртуальную машину

    - name: Install Chocolatey
      shell: cmd
      run: |
        powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
      # Устанавливает Chocolatey для управления пакетами

    - name: Install MinGW
      shell: cmd
      run: |
        choco install mingw --force -y
        echo "C:\ProgramData\mingw64\mingw64\bin" >> %GITHUB_PATH%
      # Устанавливает MinGW (компилятор g++) и добавляет его в PATH

    - name: Verify MinGW installation
      shell: cmd
      run: |
        x86_64-w64-mingw32-gcc --version
        x86_64-w64-mingw32-g++ --version
      # Проверяет, что MinGW установлен корректно

    - name: Create directories if needed
      shell: cmd
      run: |
        if not exist build mkdir build
        if not exist build_msvc\Release mkdir build_msvc\Release
      # Создаёт директории для сборки (build для MinGW, build_msvc для возможной сборки через MSVC)

    - name: Check for RustAlkadCheat2588.cpp
      shell: cmd
      run: |
        echo "Checking for RustAlkadCheat2588.cpp in DirectXSample..."
        if exist DirectXSample\RustAlkadCheat2588.cpp (
          echo "RustAlkadCheat2588.cpp found."
          dir DirectXSample\RustAlkadCheat2588.cpp
        ) else (
          echo "RustAlkadCheat2588.cpp not found in DirectXSample, listing directory contents..."
          dir DirectXSample /s
          exit /b 1
        )
      # Проверяет наличие основного файла RustAlkadCheat2588.cpp

    - name: Compile with MinGW (First Attempt)
      shell: cmd
      run: |
        echo "Starting compilation of RustAlkadCheat2588.cpp..."
        x86_64-w64-mingw32-g++ -shared -o build\RustAlkadCheat2588.dll DirectXSample\RustAlkadCheat2588.cpp -lwininet -lgdi32 -static -Wall -Wno-unknown-pragmas || (
          echo "First attempt to compile with MinGW failed, retrying..."
          x86_64-w64-mingw32-g++ -shared -o build\RustAlkadCheat2588.dll DirectXSample\RustAlkadCheat2588.cpp -lwininet -lgdi32 -static -Wall -Wno-unknown-pragmas || (
            echo "Second attempt to compile with MinGW failed, failing build..."
            exit /b 1
          )
        )
        echo "Compilation successful, DLL created at build\RustAlkadCheat2588.dll"
      # Компилирует RustAlkadCheat2588.cpp в DLL с двумя попытками
      # Флаги: -lwininet (для HTTP-запросов), -lgdi32 (для mouse_event), -static (для статической линковки)
