- name: Download ImGui
      run: |
        echo Downloading ImGui... >> logs/build.log
        curl -L -o imgui.zip https://github.com/ocornut/imgui/archive/refs/heads/master.zip && echo ImGui downloaded from primary (GitHub) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
          echo Primary ImGui download or validation failed, trying mirror 1... >> logs/build.log
          curl -L -o imgui.zip https://mirror.ghproxy.com/https://github.com/ocornut/imgui/archive/refs/heads/master.zip && echo ImGui downloaded from mirror 1 (ghproxy) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
            echo Mirror 1 failed, trying mirror 2... >> logs/build.log
            curl -L -o imgui.zip https://codeload.github.com/ocornut/imgui/zip/refs/heads/master && echo ImGui downloaded from mirror 2 (codeload) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
              echo Mirror 2 failed, trying mirror 3... >> logs/build.log
              curl -L -o imgui.zip https://web.archive.org/web/20250518000000/https://github.com/ocornut/imgui/archive/refs/heads/master.zip && echo ImGui downloaded from mirror 3 (archive.org) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                echo Mirror 3 failed, trying mirror 4... >> logs/build.log
                curl -L -o imgui.zip https://github.com/mirror-imgui/imgui/archive/refs/heads/master.zip && echo ImGui downloaded from mirror 4 (mirror-imgui) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                  echo Mirror 4 failed, trying mirror 5... >> logs/build.log
                  curl -L -o imgui.zip https://sourceforge.net/projects/imgui/files/master/imgui-master.zip && echo ImGui downloaded from mirror 5 (SourceForge) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                    echo Mirror 5 failed, trying mirror 6... >> logs/build.log
                    curl -L -o imgui.zip https://bitbucket.org/imgui-mirror/imgui/get/master.zip && echo ImGui downloaded from mirror 6 (Bitbucket) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                      echo Mirror 6 failed, trying mirror 7... >> logs/build.log
                      curl -L -o imgui.zip https://gitlab.com/imgui-mirror/imgui/-/archive/master/imgui-master.zip && echo ImGui downloaded from mirror 7 (GitLab) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                        echo Mirror 7 failed, trying mirror 8... >> logs/build.log
                        curl -L -o imgui.zip https://gitcode.net/mirrors/ocornut/imgui/-/archive/master/imgui-master.zip && echo ImGui downloaded from mirror 8 (GitCode) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                          echo Mirror 8 failed, trying mirror 9... >> logs/build.log
                          curl -L -o imgui.zip https://gitee.com/mirror-imgui/imgui/repository/archive/master.zip && echo ImGui downloaded from mirror 9 (Gitee) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                            echo Mirror 9 failed, trying mirror 10... >> logs/build.log
                            curl -L -o imgui.zip https://codeberg.org/imgui-mirror/imgui/archive/master.zip && echo ImGui downloaded from mirror 10 (Codeberg) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                              echo Mirror 10 failed, trying mirror 11... >> logs/build.log
                              curl -L -o imgui.zip https://git.savannah.gnu.org/cgit/imgui.git/snapshot/imgui-master.tar.gz && echo ImGui downloaded from mirror 11 (Savannah) >> logs/build.log && tar -tzf imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                echo Mirror 11 failed, trying mirror 12... >> logs/build.log
                                curl -L -o imgui.zip https://archive.org/download/github.com-ocornut-imgui/imgui-master.zip && echo ImGui downloaded from mirror 12 (Internet Archive) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                  echo Mirror 12 failed, trying mirror 13... >> logs/build.log
                                  curl -L -o imgui.zip https://files.phpmyadmin.net/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 13 (phpMyAdmin) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                    echo Mirror 13 failed, trying mirror 14... >> logs/build.log
                                    curl -L -o imgui.zip https://mirror.centos.org/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 14 (CentOS Mirror) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                      echo Mirror 14 failed, trying mirror 15... >> logs/build.log
                                      curl -L -o imgui.zip https://mirror.fsf.org/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 15 (FSF Mirror) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                        echo Mirror 15 failed, trying mirror 16... >> logs/build.log
                                        curl -L -o imgui.zip https://mirror.rackspace.com/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 16 (Rackspace) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                          echo Mirror 16 failed, trying mirror 17... >> logs/build.log
                                          curl -L -o imgui.zip https://mirror.netcologne.de/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 17 (NetCologne) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                            echo Mirror 17 failed, trying mirror 18... >> logs/build.log
                                            curl -L -o imgui.zip https://mirror.leaseweb.com/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 18 (Leaseweb) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                              echo Mirror 18 failed, trying mirror 19... >> logs/build.log
                                              curl -L -o imgui.zip https://mirror.nexcess.net/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 19 (Nexcess) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                echo Mirror 19 failed, trying mirror 20... >> logs/build.log
                                                curl -L -o imgui.zip https://mirror.umd.edu/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 20 (UMD) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                  echo Mirror 20 failed, trying mirror 21... >> logs/build.log
                                                  curl -L -o imgui.zip https://mirror.csclub.uwaterloo.ca/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 21 (UWaterloo) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                    echo Mirror 21 failed, trying mirror 22... >> logs/build.log
                                                    curl -L -o imgui.zip https://mirror.ox.ac.uk/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 22 (Oxford) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                      echo Mirror 22 failed, trying mirror 23... >> logs/build.log
                                                      curl -L -o imgui.zip https://mirror.yandex.ru/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 23 (Yandex) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                        echo Mirror 23 failed, trying mirror 24... >> logs/build.log
                                                        curl -L -o imgui.zip https://mirror.1und1.de/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 24 (1und1) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                          echo Mirror 24 failed, trying mirror 25... >> logs/build.log
                                                          curl -L -o imgui.zip https://mirror.easyname.at/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 25 (Easyname) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                            echo Mirror 25 failed, trying mirror 26... >> logs/build.log
                                                            curl -L -o imgui.zip https://mirror.hetzner.de/imgui/master/imgui-master.zip && echo ImGui downloaded from mirror 26 (Hetzner) >> logs/build.log && unzip -t imgui.zip >> logs/build.log 2>&1 && echo ImGui archive validated >> logs/build.log || (
                                                              echo ImGui download or validation failed from all sources >> logs/build.log
                                                              exit 1
                                                            )
                                                          )
                                                        )
                                                      )
                                                    )
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
        unzip -o imgui.zip
        echo Checking directory structure after unzip... >> logs/build.log
        dir /b /ad >> logs/build.log 2>&1
        for /f "delims=" %%i in ('dir /b /ad ^| findstr imgui-') do (
          echo Found directory: %%i >> logs/build.log
          if exist %%i (
            ren "%%i" imgui-master >> logs/build.log 2>&1
            if errorlevel 1 (
              echo Failed to rename %%i to imgui-master, forcing move... >> logs/build.log
              move "%%i" imgui-master >> logs/build.log 2>&1
            )
          ) else (
            echo Directory %%i does not exist >> logs/build.log
          )
        )
        if not exist imgui-master (
          echo Error: imgui-master directory not found after rename >> logs/build.log
          dir /s /b >> logs/build.log 2>&1
          exit 1
        )
        if not exist imgui-master\imgui.h (
          echo Warning: imgui.h not found in imgui-master, checking subdirectories... >> logs/build.log
          dir imgui-master /s /b | findstr imgui.h >> logs/build.log 2>&1
          if errorlevel 1 (
            echo Error: imgui.h not found in imgui-master or its subdirectories >> logs/build.log
            exit 1
          ) else (
            echo Moving imgui.h to imgui-master root... >> logs/build.log
            for /f "delims=" %%f in ('dir imgui-master /s /b ^| findstr imgui.h') do (
              move "%%f" imgui-master\ >> logs/build.log 2>&1
            )
          )
        ) else (
          echo imgui.h found in imgui-master >> logs/build.log
        )
        echo ImGui unzipped and structure verified >> logs/build.log
      shell: cmd
      if: steps.cache.outputs.cache-hit != 'true'
