name: Build Rust Alkad 2588 Cheat DLL

on:
  push:
    paths:
      - 'RustAlkadCheat2588.cpp'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.vcpkg
          build
          imgui
          minhook
          zlib
          json
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}-v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create log directory
      run: mkdir logs
      shell: cmd

    - name: Install 7zip
      run: choco install 7zip -y
      shell: cmd

    - name: Download ImGui
      run: |
        curl -L -o imgui.zip https://github.com/ocornut/imgui/archive/refs/heads/master.zip
        if not exist imgui.zip (echo Failed to download ImGui >> logs/build.log && exit 1)
      shell: cmd

    - name: Extract ImGui
      run: |
        7z x imgui.zip -oimgui -y
        if not exist imgui\imgui-master\imgui.h (echo Failed to extract ImGui >> logs/build.log && exit 1)
      shell: cmd

    - name: Download MinHook
      run: |
        curl -L -o minhook.zip https://github.com/TsudaKageyu/minhook/archive/refs/heads/master.zip
        if not exist minhook.zip (echo Failed to download MinHook >> logs/build.log && exit 1)
      shell: cmd

    - name: Extract MinHook
      run: |
        7z x minhook.zip -ominhook -y
        if not exist minhook\minhook-master\include\MinHook.h (echo Failed to extract MinHook >> logs/build.log && exit 1)
      shell: cmd

    - name: Download zlib
      run: |
        curl -L -o zlib.zip https://zlib.net/zlib1218.zip
        if not exist zlib.zip (echo Failed to download zlib >> logs/build.log && exit 1)
      shell: cmd

    - name: Extract zlib
      run: |
        7z x zlib.zip -ozlib -y
        if not exist zlib\zlib-1.2.18\zlib.h (echo Failed to extract zlib >> logs/build.log && exit 1)
      shell: cmd

    - name: Download nlohmann/json
      run: |
        curl -L -o json.zip https://github.com/nlohmann/json/archive/refs/heads/develop.zip
        if not exist json.zip (echo Failed to download nlohmann/json >> logs/build.log && exit 1)
      shell: cmd

    - name: Extract nlohmann/json
      run: |
        7z x json.zip -ojson -y
        if not exist json\json-develop\single_include\nlohmann\json.hpp (echo Failed to extract nlohmann/json >> logs/build.log && exit 1)
      shell: cmd

    - name: Build DLL
      run: |
        echo Building DLL... >> logs/build.log
        cl /DUNICODE /D_UNICODE /MD /O2 /W4 /FeRustAlkadCheat.dll /Iimgui/imgui-master /Iminhook/minhook-master/include /Izlib/zlib-1.2.18 /Ijson/json-develop/single_include RustAlkadCheat2588.cpp /link /DLL /OUT:RustAlkadCheat.dll 2>> logs/build.log
        if not exist RustAlkadCheat.dll (echo Build failed: DLL not created >> logs/build.log && exit 1)
      shell: cmd

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: logs/

    - name: Upload DLL
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: RustAlkadCheat
        path: RustAlkadCheat.dll
