name: Build Rust Cheat DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Установка unzip
    - name: Install unzip
      run: |
        choco install unzip
      shell: powershell

    # Настройка MSVC и Windows SDK
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        sdk: 10.0.26100.0

    # Загрузка Nuklear
    - name: Download Nuklear
      run: |
        curl -L -o nuklear.zip https://github.com/vurtun/nuklear/archive/refs/heads/master.zip
        unzip nuklear.zip
        mv nuklear-master nuklear
        # Проверка структуры директорий
        ls -R nuklear
      shell: bash
      continue-on-error: true

    # Загрузка zlib
    - name: Download and Build zlib
      run: |
        curl -L -o zlib.tar.gz https://zlib.net/zlib-1.3.1.tar.gz
        tar -xzf zlib.tar.gz
        mv zlib-1.3.1 zlib
        cd zlib
        nmake -f win32/Makefile.msc
      shell: cmd

    # Загрузка libcurl
    - name: Download and Build libcurl
      run: |
        curl -L -o curl.tar.gz https://curl.se/download/curl-8.10.1.tar.gz
        tar -xzf curl.tar.gz
        mv curl-8.10.1 curl
        cd curl/winbuild
        nmake /f Makefile.vc mode=static VC=15
      shell: cmd

    # Проверка наличия исходных файлов
    - name: Verify source files
      run: |
        dir DirectXSample\DirectXSample\RustAlkadCheat2588.cpp
        dir nuklear\nuklear_d3d11.c
      shell: cmd
      continue-on-error: true

    # Компиляция DLL
    - name: Build DLL
      run: |
        cl /LD /Fe:RustAlkadCheat2588.dll DirectXSample\DirectXSample\RustAlkadCheat2588.cpp nuklear\nuklear_d3d11.c /I nuklear /I zlib /I curl/include /link /LIBPATH:zlib /LIBPATH:curl/builds/libcurl-vc15-x64-release-static-ipv6-sspi-winssl/lib zlib.lib libcurl_a.lib psapi.lib d3d11.lib user32.lib
      shell: cmd
      env:
        VSSDKINSTALL: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VSSDK
        WindowsSdkDir: C:\Program Files (x86)\Windows Kits\10\
        WindowsSDKVersion: 10.0.26100.0\

    # Сохранение DLL как артефакта
    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: RustAlkadCheat2588
        path: RustAlkadCheat2588.dll
