name: Build Rust Alkad Cheat 2588

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        choco install mingw -y
        echo "C:\ProgramData\mingw64\mingw64\bin" >> $env:GITHUB_PATH

    - name: Install vcpkg
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies via vcpkg
      shell: cmd
      run: |
        .\vcpkg\vcpkg install imgui[dx11,win32]:x64-mingw-static minhook:x64-mingw-static nlohmann-json:x64-mingw-static zlib:x64-mingw-static --recurse
        .\vcpkg\vcpkg integrate install

    - name: Install CMake
      uses: lukka/get-cmake@v3.29.0
      with:
        cmakeVersion: '3.29.0'

    - name: Configure CMake
      shell: cmd
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++

    - name: Build
      shell: cmd
      run: |
        cmake --build build --config Release --parallel

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RustAlkadCheat2588
        path: build/RustAlkadCheat2588.dll
