name: Build Rust Alkad 2588 Cheat DLL

on:
  push:
    paths:
      - 'RustAlkadCheat2588.cpp'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.vcpkg
          build
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create log directory
      run: mkdir logs

    - name: Install 7zip
      run: choco install 7zip -y
      shell: cmd

    - name: Download ImGui
      run: curl -L -o imgui.zip https://github.com/ocornut/imgui/archive/refs/heads/master.zip

    - name: Extract ImGui
      run: 7z x imgui.zip -oimgui -y
      shell: cmd

    - name: Download MinHook
      run: curl -L -o minhook.zip https://github.com/TsudaKageyu/minhook/archive/refs/heads/master.zip

    - name: Extract MinHook
      run: 7z x minhook.zip -ominhook -y
      shell: cmd

    - name: Download zlib
      run: curl -L -o zlib.zip https://zlib.net/zlib1218.zip

    - name: Extract zlib
      run: 7z x zlib.zip -ozlib -y
      shell: cmd

    - name: Download nlohmann/json
      run: curl -L -o json.zip https://github.com/nlohmann/json/archive/refs/heads/develop.zip

    - name: Extract nlohmann/json
      run: 7z x json.zip -ojson -y
      shell: cmd

    - name: Build DLL
      run: |
        echo Building DLL... >> logs/build.log
        cl /DUNICODE /D_UNICODE /MD /O2 /W4 /FeRustAlkadCheat.dll /Iimgui/imgui-master /Iminhook/minhook-master/include /Izlib/zlib-1.2.18 /Ijson/json-develop/single_include RustAlkadCheat2588.cpp /link imgui.lib minhook.lib zlib.lib /OUT:RustAlkadCheat.dll
      shell: cmd

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: logs/

    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: RustAlkadCheat
        path: RustAlkadCheat.dll
