name: Build Rust Alkad Cheat 2588

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Chocolatey
      shell: cmd
      run: |
        powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"

    - name: Install MinGW
      shell: cmd
      run: |
        choco install mingw --force -y
        echo "C:\ProgramData\mingw64\mingw64\bin" >> %GITHUB_PATH%

    - name: Install 7zip
      shell: cmd
      run: |
        choco install 7zip --force -y

    - name: Install DirectX SDK
      shell: cmd
      run: |
        set DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)
        if not exist "%DXSDK_DIR%" (
          echo "DirectX SDK not found, downloading from internet..."
          curl -L -o DXSDK_Jun10.exe https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe || (
            echo "Failed to download from Microsoft, trying mirrors..."
            curl -L -o DXSDK_Jun10.exe https://archive.org/download/dxsdk_jun10/DXSDK_Jun10.exe || (
              curl -L -o DXSDK_Jun10.exe https://web.archive.org/web/20150610223024/https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe || (
                curl -L -o DXSDK_Jun10.exe https://download.gamedev.net/sdk/directx/DirectX%20SDK%20(Jun%202010)/DXSDK_Jun10.exe || (
                  curl -L -o DXSDK_Jun10.exe https://www.mirrorservice.org/sites/dl.eccentrica.org/public/ms/DirectX/DXSDK_Jun10.exe || (
                    curl -L -o DXSDK_Jun10.exe https://ftp.gwdg.de/pub/misc/microsoft/DirectX/DXSDK_Jun10.exe || (
                      curl -L -o DXSDK_Jun10.exe https://mirrors.kernel.org/microsoft/DirectX/DXSDK_Jun10.exe || (
                        curl -L -o DXSDK_Jun10.exe https://archive.org/download/DXSDK_Jun10_202205/DXSDK_Jun10.exe || (
                          curl -L -o DXSDK_Jun10.exe https://download.nvidia.com/developer/directx_sdk/DXSDK_Jun10.exe || (
                            curl -L -o DXSDK_Jun10.exe https://www.dll-files.com/DXSDK_Jun10.exe || (
                              echo "All DirectX SDK download attempts failed, trying Chocolatey as fallback..."
                              choco install directx-sdk --force -y || (
                                echo "DirectX SDK installation failed via all methods, exiting..."
                                exit /b 1
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
          echo "Installing DirectX SDK..."
          start /wait DXSDK_Jun10.exe /S
          if not exist "%DXSDK_DIR%" (
            echo "DirectX SDK installation failed, directory not found."
            exit /b 1
          )
          echo "DirectX SDK installed at %DXSDK_DIR%"
        ) else (
          echo "DirectX SDK already found at %DXSDK_DIR%"
        )

    - name: Download and extract nlohmann-json
      shell: cmd
      run: |
        if exist json\single_include\nlohmann\json.hpp (
          echo "Local nlohmann-json found, skipping download."
        ) else (
          echo "Local nlohmann-json not found, downloading..."
          curl -L -o json.zip https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.zip || (
            echo "Failed to download nlohmann-json v3.11.3, trying mirrors..."
            curl -L -o json.zip https://github.com/nlohmann/json/archive/refs/heads/develop.zip || (
              curl -L -o json.zip https://github.com/ArthurSonzogni/nlohmann_json_cmake_fetchcontent/archive/refs/heads/master.zip || (
                curl -L -o json.zip https://github.com/jarro2783/json/archive/refs/heads/master.zip || (
                  curl -L -o json.zip https://github.com/axoloti/nlohmann_json/archive/refs/heads/master.zip || (
                    curl -L -o json.zip https://github.com/pboettch/json-schema-validator/archive/refs/heads/master.zip || (
                      curl -L -o json.zip https://github.com/nlohmann/json/releases/download/v3.11.3/json-3.11.3.zip || (
                        curl -L -o json.zip https://github.com/martinmoene/nlohmann_json_single/archive/refs/heads/master.zip || (
                          curl -L -o json.zip https://github.com/Hydrazer/nlohmann-json/archive/refs/heads/master.zip || (
                            curl -L -o json.zip https://github.com/tburette/nlohmann_json/archive/refs/heads/master.zip || (
                              curl -L -o json.zip https://gitlab.com/nlohmann/json/-/archive/v3.11.3/json-v3.11.3.zip || (
                                curl -L -o json.zip https://gitlab.com/nlohmann/json/-/archive/master/json-master.zip || (
                                  curl -L -o json.zip https://bitbucket.org/nlohmann/json/downloads/json-3.11.3.zip || (
                                    curl -L -o json.zip https://bitbucket.org/nlohmann/json/downloads/master.zip || (
                                      curl -L -o json.zip https://codeberg.org/nlohmann/json/archive/v3.11.3.zip || (
                                        curl -L -o json.zip https://codeberg.org/nlohmann/json/archive/master.zip || (
                                          curl -L -o json.zip https://gitlab.com/martinmoene/nlohmann_json_single/-/archive/master/nlohmann_json_single-master.zip || (
                                            curl -L -o json.zip https://github.com/nlohmann/json-mirror/archive/refs/tags/v3.11.3.zip || (
                                              echo "All nlohmann-json download attempts failed, exiting..."
                                              exit /b 1
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
          echo "Extracting json.zip..."
          7z x json.zip -ojson_temp
          dir json_temp
          if exist json_temp\json-3.11.3\single_include (
            move json_temp\json-3.11.3\single_include json\
          ) else if exist json_temp\json-develop\single_include (
            move json_temp\json-develop\single_include json\
          ) else if exist json_temp\json-master\single_include (
            move json_temp\json-master\single_include json\
          ) else if exist json_temp\nlohmann-json-v3.11.3\single_include (
            move json_temp\nlohmann-json-v3.11.3\single_include json\
          ) else (
            for /d %%i in (json_temp\*) do (
              if exist "%%i\single_include" (
                move "%%i\single_include" json\
              ) else (
                echo "No single_include folder found in %%i"
              )
            )
          )
          dir json
          if exist json\single_include\nlohmann\json.hpp (
            echo "nlohmann-json successfully extracted."
          ) else (
            echo "Failed to extract nlohmann-json, json.hpp not found. Checking contents..."
            dir json /s
            exit /b 1
          )
          rmdir /s /q json_temp
        )

    - name: Verify MinGW installation
      shell: cmd
      run: |
        x86_64-w64-mingw32-gcc --version
        x86_64-w64-mingw32-g++ --version

    - name: Create directories if needed
      shell: cmd
      run: |
        if not exist build mkdir build
        if not exist build_msvc\Release mkdir build_msvc\Release

    - name: Compile with MinGW (First Attempt)
      shell: cmd
      run: |
        if exist DirectXSample\RustAlkadCheat2588.cpp (
          echo "Using DirectX SDK at %DXSDK_DIR%"
          x86_64-w64-mingw32-g++ -shared -o build\RustAlkadCheat2588.dll DirectXSample\RustAlkadCheat2588.cpp -Ijson\single_include -L"%DXSDK_DIR%\Lib\x86" -lgdi32 -ld3d9 -ld3dx9 -static -Wall -Wno-unknown-pragmas || (
            echo "First attempt to compile with MinGW failed, retrying..."
            x86_64-w64-mingw32-g++ -shared -o build\RustAlkadCheat2588.dll DirectXSample\RustAlkadCheat2588.cpp -Ijson\single_include -L"%DXSDK_DIR%\Lib\x86" -lgdi32 -ld3d9 -ld3dx9 -static -Wall -Wno-unknown-pragmas
          )
        ) else (
          echo "Could not find RustAlkadCheat2588.cpp, failing build"
          exit /b 1
        )

    - name: Compile with MSVC (Fallback)
      if: failure()
      shell: cmd
      run: |
        if exist DirectXSample\RustAlkadCheat2588.cpp (
          echo "Using DirectX SDK at %DXSDK_DIR%"
          cl /D_CRT_SECURE_NO_WARNINGS /W0 /DUNICODE /D_UNICODE /MD /LD DirectXSample\RustAlkadCheat2588.cpp /Febuild_msvc\Release\RustAlkadCheat2588.dll /Ijson\single_include /link /LIBPATH:"%DXSDK_DIR%\Lib\x86" gdi32.lib d3d9.lib d3dx9.lib || (
            echo "MSVC compilation failed, retrying..."
            cl /D_CRT_SECURE_NO_WARNINGS /W0 /DUNICODE /D_UNICODE /MD /LD DirectXSample\RustAlkadCheat2588.cpp /Febuild_msvc\Release\RustAlkadCheat2588.dll /Ijson\single_include /link /LIBPATH:"%DXSDK_DIR%\Lib\x86" gdi32.lib d3d9.lib d3dx9.lib
          )
        ) else (
          echo "Could not find RustAlkadCheat2588.cpp, failing build"
          exit /b 1
        )

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RustAlkadCheat2588
        path: |
          build/RustAlkadCheat2588.dll
          build_msvc/Release/RustAlkadCheat2588.dll
