name: Build Rust Alkad 2588 Cheat DLL

on:
  push: # Запускаем при изменении любых файлов
  workflow_dispatch: # Ручной запуск

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          imgui
          minhook
          zlib
          json
        key: ${{ runner.os }}-deps-${{ hashFiles('RustAlkadCheat2588.cpp') }}-v1

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create log directory
      run: New-Item -ItemType Directory -Path logs -Force
      shell: powershell

    - name: Download ImGui
      run: |
        $urls = @(
          "https://github.com/ocornut/imgui/archive/refs/heads/master.zip",
          "https://github.com/ocornut/imgui/archive/master.zip",
          "https://gitlab.com/mirror/imgui/-/archive/master/imgui-master.zip"
        )
        $downloaded = $false
        foreach ($url in $urls) {
          try {
            Invoke-WebRequest -Uri $url -OutFile imgui.zip
            $downloaded = $true
            Write-Output "Downloaded ImGui from $url" | Out-File -FilePath logs/build.log -Append
            break
          } catch {
            Write-Output "Failed to download ImGui from $url" | Out-File -FilePath logs/build.log -Append
          }
        }
        if (-not $downloaded) { Write-Output "Failed to download ImGui from all URLs" | Out-File -FilePath logs/build.log -Append; exit 1 }
        if (-not (Test-Path imgui.zip)) { Write-Output "ImGui zip not found after download" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Extract ImGui
      run: |
        Expand-Archive -Path imgui.zip -DestinationPath imgui -Force
        if (-not (Test-Path imgui/imgui-master/imgui.h)) { Write-Output "Failed to extract ImGui" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Download MinHook
      run: |
        $urls = @(
          "https://github.com/TsudaKageyu/minhook/archive/refs/heads/master.zip",
          "https://github.com/TsudaKageyu/minhook/archive/master.zip",
          "https://gitlab.com/mirrors/minhook/-/archive/master/minhook-master.zip"
        )
        $downloaded = $false
        foreach ($url in $urls) {
          try {
            Invoke-WebRequest -Uri $url -OutFile minhook.zip
            $downloaded = $true
            Write-Output "Downloaded MinHook from $url" | Out-File -FilePath logs/build.log -Append
            break
          } catch {
            Write-Output "Failed to download MinHook from $url" | Out-File -FilePath logs/build.log -Append
          }
        }
        if (-not $downloaded) { Write-Output "Failed to download MinHook from all URLs" | Out-File -FilePath logs/build.log -Append; exit 1 }
        if (-not (Test-Path minhook.zip)) { Write-Output "MinHook zip not found after download" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Extract MinHook
      run: |
        Expand-Archive -Path minhook.zip -DestinationPath minhook -Force
        if (-not (Test-Path minhook/minhook-master/include/MinHook.h)) { Write-Output "Failed to extract MinHook" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Download zlib
      run: |
        $urls = @(
          "https://zlib.net/zlib-1.2.13.zip",
          "https://www.zlib.net/zlib1213.zip",
          "https://sourceforge.net/projects/libpng/files/zlib/1.2.13/zlib-1.2.13.zip/download"
        )
        $downloaded = $false
        foreach ($url in $urls) {
          try {
            Invoke-WebRequest -Uri $url -OutFile zlib.zip
            $downloaded = $true
            Write-Output "Downloaded zlib from $url" | Out-File -FilePath logs/build.log -Append
            break
          } catch {
            Write-Output "Failed to download zlib from $url" | Out-File -FilePath logs/build.log -Append
          }
        }
        if (-not $downloaded) { Write-Output "Failed to download zlib from all URLs" | Out-File -FilePath logs/build.log -Append; exit 1 }
        if (-not (Test-Path zlib.zip)) { Write-Output "zlib zip not found after download" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Extract zlib
      run: |
        Expand-Archive -Path zlib.zip -DestinationPath zlib -Force
        if (-not (Test-Path zlib/zlib-1.2.18/zlib.h)) { Write-Output "Failed to extract zlib" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Download nlohmann/json
      run: |
        $urls = @(
          "https://github.com/nlohmann/json/archive/refs/heads/develop.zip",
          "https://github.com/nlohmann/json/archive/develop.zip",
          "https://gitlab.com/mirrors/nlohmann-json/-/archive/develop/nlohmann-json-develop.zip"
        )
        $downloaded = $false
        foreach ($url in $urls) {
          try {
            Invoke-WebRequest -Uri $url -OutFile json.zip
            $downloaded = $true
            Write-Output "Downloaded nlohmann/json from $url" | Out-File -FilePath logs/build.log -Append
            break
          } catch {
            Write-Output "Failed to download nlohmann/json from $url" | Out-File -FilePath logs/build.log -Append
          }
        }
        if (-not $downloaded) { Write-Output "Failed to download nlohmann/json from all URLs" | Out-File -FilePath logs/build.log -Append; exit 1 }
        if (-not (Test-Path json.zip)) { Write-Output "nlohmann/json zip not found after download" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Extract nlohmann/json
      run: |
        Expand-Archive -Path json.zip -DestinationPath json -Force
        if (-not (Test-Path json/json-develop/single_include/nlohmann/json.hpp)) { Write-Output "Failed to extract nlohmann/json" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: powershell

    - name: Build DLL
      run: |
        Write-Output "Building DLL..." | Out-File -FilePath logs/build.log -Append
        cl /DUNICODE /D_UNICODE /MD /O2 /W4 /FeRustAlkadCheat.dll /Iimgui/imgui-master /Iminhook/minhook-master/include /Izlib/zlib-1.2.18 /Ijson/json-develop/single_include RustAlkadCheat2588.cpp /link /DLL /OUT:RustAlkadCheat.dll 2>> logs/build.log
        if (-not (Test-Path RustAlkadCheat.dll)) { Write-Output "Build failed: DLL not created" | Out-File -FilePath logs/build.log -Append; exit 1 }
      shell: cmd

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: logs/

    - name: Upload DLL
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: RustAlkadCheat
        path: RustAlkadCheat.dll
